Gemfile, Gemfile.lock, app/controllers/omniauth_callbacks_controller.rb, app/controllers/welcome_controller.rb, app/javascript/actions/auth.js, app/javascript/components/AppLayout.jsx, app/javascript/packs/application.js, app/javascript/reducers/auth.js, app/javascript/reducers/index.js, app/javascript/ui/Header.jsx, app/javascript/ui/UserMenu.jsx, app/javascript/utils/types.jsx, app/models/identity.rb, app/models/user.rb, app/views/welcome/index.html.erb, app/views/welcome/landing.html.erb, config/guisso.yml, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20171121172440_devise_create_users.rb, db/migrate/20171121172925_create_identities.rb, db/schema.rb, spec/models/user_spec.rb
=> Implement user authentication using Guisso

app/models/behaviour.rb, app/models/bot.rb, app/schemas/types.json, db/migrate/20171124193432_create_behaviours.rb, db/schema.rb, spec/models/bot_spec.rb
=> Create behaviours table and create front_desk for new bots

app/controllers/api/front_desks_controller.rb, app/javascript/actions/channel.js, app/javascript/actions/frontDesk.js, app/javascript/app/application.jsx, app/javascript/components/BotBehaviour.jsx, app/javascript/components/FrontDesk.jsx, app/javascript/reducers/frontDesk.js, app/javascript/reducers/index.js, app/javascript/ui/Field.jsx, app/javascript/utils/api.js, app/javascript/utils/index.js, app/javascript/utils/types-generated-decl.jsx, app/javascript/utils/types.jsx, app/schemas/types.json, config/routes.rb, package.json, spec/controllers/api/front_desks_controller_spec.rb, yarn.lock
=> UI to update front desk behaviour

app/controllers/api/skills_controller.rb, app/controllers/application_api_controller.rb, app/javascript/actions/skill.js, app/javascript/actions/skills.js, app/javascript/components/BotBehaviour.jsx, app/javascript/components/BotLayout.jsx, app/javascript/components/BotSkill.jsx, app/javascript/components/SkillsBar.jsx, app/javascript/reducers/index.js, app/javascript/reducers/skills.js, app/javascript/ui/Header.jsx, app/javascript/utils/api.js, app/javascript/utils/routes.js, app/javascript/utils/types-generated-decl.jsx, app/javascript/utils/types.jsx, app/models/behaviour.rb, app/schemas/types.json, config/routes.rb, spec/controllers/api/skills_controller_spec.rb
=> Create empty skills from UI

app/javascript/actions/skill.js, app/javascript/components/BotSkill.jsx, app/javascript/components/KeywordResponder.jsx, app/javascript/utils/types-generated-decl.jsx, app/models/behaviour.rb, app/models/bot.rb, app/schemas/types.json
=> Keyword responder configuration UI

app/javascript/components/BotSkill.jsx, app/javascript/components/LanguageDetector.jsx, app/javascript/components/LanguageSelector.jsx, app/javascript/ui/css/_global.scss, app/javascript/utils/types-generated-decl.jsx, app/models/behaviour.rb, app/schemas/types.json, package.json, spec/controllers/api/skills_controller_spec.rb, yarn.lock
=> Language detector UI

app/javascript/actions/skill.js, app/models/behaviour.rb, app/models/bot.rb, spec/models/behaviour_spec.rb, spec/models/bot_spec.rb
=> Toggle skills from UI

app/controllers/api/skills_controller.rb, app/javascript/actions/skill.js, app/javascript/actions/skills.js, app/javascript/components/KeywordResponder.jsx, app/javascript/components/SkillsBar.jsx, app/javascript/reducers/skills.js, app/javascript/utils/api.js, app/javascript/utils/types.jsx, spec/controllers/api/skills_controller_spec.rb
=> Rename and delete skills from the UI

app/controllers/api/translations_controller.rb, app/javascript/actions/translations.js, app/javascript/components/BotLayout.jsx, app/javascript/components/BotTranslations.jsx, app/javascript/components/LanguageSelector.jsx, app/javascript/reducers/index.js, app/javascript/reducers/translations.js, app/javascript/ui/Field.jsx, app/javascript/ui/MainContent.jsx, app/javascript/ui/css/_global.scss, app/javascript/ui/css/_grid.scss, app/javascript/utils/api.js, app/javascript/utils/lang.js, app/javascript/utils/routes.js, app/javascript/utils/types.jsx, app/models/behaviour.rb, app/models/bot.rb, app/models/translation.rb, config/routes.rb, db/migrate/20171204175114_create_translations.rb, db/schema.rb, spec/controllers/api/translations_controller_spec.rb, spec/models/behaviour_spec.rb, spec/models/bot_spec.rb, spec/models/translation_spec.rb
=> Message translations

app/controllers/api/bots_controller.rb, app/javascript/actions/bot.js, app/javascript/app/design.jsx, app/javascript/components/AppLayout.jsx, app/javascript/components/BotLayout.jsx, app/javascript/ui/Header.jsx, app/javascript/utils/api.js, app/javascript/utils/types.jsx, app/services/publish_bot.rb, app/services/unpublish_bot.rb, config/routes.rb
Closes #34 
Built on top of PR #33
=> Unpublish a bot

app/controllers/api/bots_controller.rb, app/controllers/application_api_controller.rb, app/javascript/actions/stats.js, app/javascript/reducers/index.js, app/javascript/reducers/stats.js, app/javascript/utils/api.js, app/javascript/utils/types.jsx, app/lib/backend.rb, app/services/gather_bot_stats.rb, config/routes.rb
=> API endpoint to gather stats for a bot

app/controllers/api/bots_controller.rb, app/javascript/actions/bot.js, app/javascript/components/BotLayout.jsx, app/javascript/reducers/bots.js, app/javascript/utils/api.js, app/javascript/utils/routes.js, app/javascript/utils/types.jsx, config/routes.rb, config/settings/test.yml, spec/controllers/api/bots_controller_spec.rb, spec/requests/deep_links_spec.rb, spec/support/backend_mock.rb
=> Implementation for deleting bots

app/controllers/api/bots_controller.rb, app/javascript/components/BotIndex.jsx, spec/controllers/api/bots_controller_spec.rb
=> UI when the user has no bots; don't create a bot automatically

app/javascript/app/design.jsx, app/javascript/components/BotBehaviour.jsx, app/javascript/components/BotChannel.jsx, app/javascript/components/BotTranslations.jsx, app/javascript/ui/MainWhite.jsx, app/javascript/ui/SingleColumn.jsx, app/javascript/ui/css/_global.scss, app/javascript/ui/css/_layout.scss, app/javascript/ui/css/_main.scss
Ref #25 Add SingleColumn layout
=> Add SingleColumn layout

app/javascript/ui/Header.jsx, app/javascript/ui/css/App.scss, app/javascript/ui/css/_global.scss, app/javascript/ui/css/_header.scss, app/javascript/ui/css/_layout.scss, app/javascript/ui/css/_overrides.scss
Set fixed width and check responsive styles
=> Fix navigation bar flickering when resizing

app/javascript/ui/css/_sidebar.scss
Fix #71. Make active class apply only to skill item
=> Fix #71. Make active class apply only to skill item

app/controllers/api/bots_controller.rb, app/javascript/actions/bot.js, app/javascript/components/BotLayout.jsx, app/javascript/utils/api.js, app/policies/bot_policy.rb, app/services/duplicate_bot.rb, config/routes.rb, spec/controllers/api/bots_controller_spec.rb, spec/policies/bot_policy_spec.rb, spec/services/duplicate_bot_spec.rb
=> Duplicate a bot

app/javascript/components/RelevanceField.jsx, app/javascript/components/css/_relevance.scss, app/javascript/ui/Field.jsx
Fix #74. Make relevance field resizable
=> Fix #74. Text gets cut in relevance field

app/javascript/components/ScheduledMessages.jsx, app/javascript/ui/KeyValueListField.jsx, app/javascript/ui/css/_global.scss, app/javascript/ui/css/_main.scss, app/javascript/ui/css/_overrides.scss
Fix #73. Layout and font of select in Behaviour
=> Fix #73. Layout and font of select in Behaviour

app/javascript/components/ChatWindow.jsx, app/javascript/components/css/_chat_window.scss
=> Show consecutive messages together

app/javascript/components/ScheduledMessages.jsx, app/javascript/components/Survey.jsx, app/javascript/utils/index.js, package.json, yarn.lock
=> Set the timezone in the date pickers to the local timezone

app/controllers/api/bots_controller.rb, app/javascript/actions/bot.js, app/javascript/components/BotLayout.jsx, app/javascript/utils/types-generated-decl.jsx, app/policies/bot_policy.rb, app/policies/collaborator_policy.rb, app/schemas/types.json, spec/controllers/api/collaborators_controller_spec.rb, spec/policies/collaborator_policy_spec.rb
Closes #97 
Built on top of #101
=> Allow collaborators to leave bots

app/javascript/app/application.scss, app/javascript/components/BotTranslations.jsx, app/javascript/components/BotTranslationsVariables.jsx, app/javascript/components/LanguageDetector.jsx, app/javascript/components/ScheduledMessages.jsx, app/javascript/components/css/_translations.scss, app/javascript/ui/KeyValueListField.jsx, app/javascript/ui/css/_global.scss
Fix #99. Add indicator of editable content to table's input fields
=> Fix #99. Add indicator of editable content to table's input fields

app/javascript/components/ScheduledMessages.jsx, app/javascript/components/css/_skills.scss, app/javascript/ui/css/_global.scss, app/javascript/utils/types-generated-decl.jsx, app/models/behaviour.rb, app/schemas/types.json, spec/models/behaviour_spec.rb
=> Support recurrent scheduled messages

app/javascript/components/ScheduledMessages.jsx, app/javascript/utils/types-generated-decl.jsx, app/models/behaviour.rb, app/schemas/types.json, db/migrate/20180122145329_add_delay_unit_in_scheduled_messages.rb, db/schema.rb
Built on top of #111 
Closes #92
=> Support arbitrary delays when specifying inactivity intervals for scheduled messages

app/javascript/components/BotCollaborators.jsx, app/javascript/components/SettingsApi.jsx, app/javascript/utils/routes.js
=> Ensure that site links are properly constructed from window.baseUrl

app/models/variable_assignment.rb, spec/models/variable_assignment_spec.rb
=> Fix condition with value and no key

app/javascript/app/application.scss, app/javascript/components/BotSkill.jsx, app/javascript/components/DecisionTree.jsx, app/javascript/components/SkillsBar.jsx, app/javascript/components/css/_decision_tree.scss, app/javascript/utils/types-generated-decl.jsx, app/models/behaviour.rb, app/schemas/types.json
=> Decision Tree Component

app/javascript/components/DecisionTree.jsx
=> Fix removing option without siblings

app/controllers/api/sessions_controller.rb, app/javascript/components/SettingsApi.jsx, app/lib/backend.rb, config/routes.rb
=> Add API for sessions information and session log

app/controllers/api/encryption_keys_controller.rb, app/javascript/actions/keypair.js, app/javascript/app/application.jsx, app/javascript/components/AppLayout.jsx, app/javascript/components/SettingsEncryption.jsx, app/javascript/components/css/_settings.scss, app/javascript/reducers/index.js, app/javascript/reducers/keypair.js, app/javascript/utils/api.js, app/javascript/utils/routes.js, app/javascript/utils/types-generated-decl.jsx, app/javascript/utils/types.jsx, app/schemas/types.json, config/routes.rb, db/migrate/20180130192612_add_keypair_to_users.rb, db/schema.rb, package.json, yarn.lock
=> Define encryption keys with a passphrase

app/javascript/components/BotCollaborators.jsx, app/javascript/components/TablesIndex.jsx
Fix #134 'variables' collaboration permission is now 'variables and tables'
=> #134 adding tables so they can be shared with collaborators

app/controllers/api/bots_controller.rb, app/javascript/actions/errorLogs.js, app/javascript/components/BotErrorLogs.jsx, app/javascript/components/BotLayout.jsx, app/javascript/reducers/errorLogs.js, app/javascript/reducers/index.js, app/javascript/ui/css/_header.scss, app/javascript/utils/api.js, app/javascript/utils/routes.js, app/javascript/utils/types.jsx, app/lib/backend.rb, app/policies/bot_policy.rb, app/schemas/types.json, app/services/gather_bot_error_logs.rb, config/routes.rb, spec/controllers/api/bots_controller_spec.rb, spec/support/matchers.rb
=> Add Error Log support

app/javascript/actions/chat.js, app/javascript/components/BotLayout.jsx, app/javascript/components/ChatClient.jsx, app/javascript/components/ChatWindow.jsx, app/javascript/components/css/_chat_window.scss, app/javascript/reducers/chat.js, app/javascript/utils/backend.js, app/javascript/utils/types.jsx, app/views/welcome/index.html.erb
Add image attachments support to chat simulator.
We should track the few UI improvements that can already be done in a separate ticket.
Fixes instedd/aida#64
=> Simulator attachments

app/javascript/components/FrontDesk.jsx, app/javascript/utils/types-generated-decl.jsx, app/models/behaviour.rb, app/schemas/types.json, db/migrate/20180706130248_add_unsubscribe_to_front_desk.rb, db/schema.rb, spec/controllers/api/front_desks_controller_spec.rb, spec/models/behaviour_spec.rb, spec/models/bot_spec.rb, spec/services/duplicate_bot_spec.rb
Set up unsubscribe properties for the corresponding backend feature.
For instedd/aida#173
=> Add unsubscribe to front desk

app/javascript/components/BotChannel.jsx, app/javascript/components/TooltipFontIcon.jsx
To the information tooltip.
Relating to Facebook prelaunch checklist and platform policy.
Resolves #163
=> Add a TLDR on the facebook channel creation

app/javascript/components/BotAnalytics.jsx, app/javascript/components/BotBehaviour.jsx, app/javascript/ui/FabButton.jsx
And some refactoring for avoiding warnings.
Fixes instedd/aida#228
=>  Fix bug bots cannot be published

app/assets/stylesheets/_variables.scss, app/controllers/api/bots_controller.rb, app/javascript/actions/bot.js, app/javascript/actions/chat.js, app/javascript/components/BotChannel.jsx, app/javascript/components/BotLayout.jsx, app/javascript/components/BotSkill.jsx, app/javascript/components/DecisionTree.jsx, app/javascript/components/FrontDesk.jsx, app/javascript/components/FrontDeskItem.jsx, app/javascript/components/KeywordResponder.jsx, app/javascript/components/SkillListItem.jsx, app/javascript/components/SkillsBar.jsx, app/javascript/components/Survey.jsx, app/javascript/reducers/bots.js, app/javascript/reducers/chat.js, app/javascript/ui/Field.jsx, app/javascript/ui/Header.jsx, app/javascript/ui/SideBar.jsx, app/javascript/ui/css/_header.scss, app/javascript/ui/css/_sidebar.scss, app/javascript/ui/css/_variables-overrides.scss, app/javascript/utils/types.jsx, app/lib/backend_error.rb, app/services/publish_bot.rb, spec/lib/backend_error_spec.rb
=> WIP Show errors on bot publication

app/javascript/components/BotAnalytics.jsx, app/javascript/components/BotBehaviour.jsx
And refactor BotBehaviour (remove extrinsic code added by error in 9d718e2)
Fix instedd/aida#228
=> Fix publish bot from BotAnalytics

app/javascript/components/BotBehaviour.jsx, app/javascript/components/BotSkill.jsx, app/javascript/components/DecisionTree.jsx, app/javascript/components/FrontDesk.jsx, app/javascript/components/KeywordResponder.jsx, app/javascript/components/SkillsBar.jsx, app/javascript/components/Survey.jsx, app/javascript/ui/css/_global.scss, app/lib/backend_error.rb, spec/lib/backend_error_spec.rb
Depends on #174. Please merge first #174 and then this one. For #171.
And fix bug parsing duplicated skill error. Related to #147.
=> Show errors in DecisionTreeComponent

app/javascript/components/HumanOverride.jsx
=> Show errors in HumanOverride component

app/javascript/components/ScheduledMessages.jsx, app/javascript/reducers/bots.js, app/lib/backend_error.rb, spec/lib/backend_error_spec.rb
=> Show errors in scheduled messages

app/javascript/components/AppLayout.jsx
=> Added counter to AppLayout

app/javascript/components/DecisionTree.jsx, app/lib/backend_error.rb, spec/lib/backend_error_spec.rb
=> Shor errors in decision trees

app/controllers/api/bots_controller.rb, app/javascript/components/BotChannel.jsx, app/javascript/utils/types-generated-decl.jsx, app/schemas/types.json
=> Include bot id in facebook callback url

app/javascript/actions/bot.js, app/javascript/components/BotIndex.jsx, app/javascript/reducers/bots.js, app/javascript/utils/types.jsx
=> Clean errors on bot selection

app/controllers/welcome_controller.rb
=> Redirect to home when not logged in

app/controllers/api/collaborators_controller.rb, app/javascript/components/BotSkill.jsx, app/javascript/components/HumanOverride.jsx, app/javascript/utils/types-generated-decl.jsx, app/schemas/types.json
Resolves instedd/aida#221
Technical debt: #204
=> Show operators in human override

app/javascript/reducers/bots.js
=> Clean errors on bot creation

app/controllers/api/bots_controller.rb, app/controllers/api/channels_controller.rb, app/javascript/actions/channel.js, app/javascript/actions/channels.js, app/javascript/components/BotChannel.jsx, app/javascript/components/BotChannelFacebook.jsx, app/javascript/components/BotChannelIndex.jsx, app/javascript/components/BotChannelWebSocket.jsx, app/javascript/components/BotLayout.jsx, app/javascript/reducers/bots.js, app/javascript/reducers/channels.js, app/javascript/ui/css/_global.scss, app/javascript/utils/api.js, app/javascript/utils/routes.js, app/javascript/utils/types.jsx, app/models/bot.rb, app/models/channel.rb, app/policies/channel_policy.rb, config/routes.rb, spec/controllers/api/channels_controller_spec.rb, spec/models/bot_spec.rb, spec/policies/channel_policy_spec.rb, spec/services/duplicate_bot_spec.rb
Resolves #207 
Technical debt: #214, #215
=> Add channel CRUD

app/javascript/components/HumanOverride.jsx, app/javascript/ui/css/_forms.scss, app/javascript/ui/css/_global.scss
=> Fixes #204 - Style operator button in human override

app/controllers/api/channels_controller.rb, app/javascript/actions/bot.js, app/javascript/components/DecisionTree.jsx, app/javascript/components/HumanOverride.jsx, app/javascript/components/KeywordResponder.jsx, app/javascript/components/SkillsBar.jsx, app/javascript/components/Survey.jsx, app/javascript/ui/KeywordInput.jsx, app/javascript/utils/types-generated-decl.jsx, app/lib/backend_error.rb, app/models/behaviour.rb, app/models/bot.rb, app/schemas/types.json, spec/controllers/api/channels_controller_spec.rb, spec/lib/backend_error_spec.rb, spec/models/behaviour_spec.rb, spec/models/bot_spec.rb
Resolves #190 
Resolves #191 
Resolves #220
Technical debt: #224
=> Add Wit.ai

app/controllers/api/messages_controller.rb, app/controllers/api/notifications_controller.rb, app/javascript/actions/messages.js, app/javascript/components/HumanOverrideChatWindow.jsx, app/javascript/components/Messages.jsx, app/javascript/reducers/messages.js, app/javascript/utils/api.js, app/javascript/utils/types-generated-decl.jsx, app/javascript/utils/types.jsx, app/lib/backend.rb, app/models/notification.rb, app/schemas/types.json, config/routes.rb, db/migrate/20180906211836_add_uuid_to_notifications.rb, db/migrate/20180914133242_add_session_uuid_to_notifications.rb, db/schema.rb, spec/controllers/api/messages_controller_spec.rb, spec/controllers/api/notifications_controller_spec.rb, spec/factories.rb, spec/models/notification_spec.rb
Depends on instedd/aida#264
Resolves #229 
Resolves instedd/aida#262
Technical debt: #234
=> Human override operator takes control of the bot session

app/javascript/components/BotSkill.jsx, app/javascript/components/LanguageDetector.jsx, app/javascript/components/LanguageSelector.jsx, app/javascript/components/SkillsBar.jsx
=> Show errors in skill fields

Gemfile, Gemfile.lock, config/cable.yml, docker-compose.yml
=> Add Redis Gem

app/controllers/api/bots_controller.rb, app/javascript/actions/bot.js, app/javascript/reducers/bots.js, app/javascript/utils/types.jsx, spec/controllers/api/bots_controller_spec.rb
=> Set uuid after publish

app/javascript/reducers/bots.js
=> Clear errors when bot updates

app/javascript/actions/chat.js, app/javascript/components/ChatClient.jsx, app/javascript/components/ChatWindow.jsx, app/javascript/reducers/chat.js, app/javascript/utils/types.jsx
Depends on instedd/aida#279
Fixes instedd/aida#275
Co-authored-by: Matias Garcia Isaia <mgarcia@manas.tech>
=> Retry connecting preview chat while bot is starting

Gemfile, Gemfile.lock, app/controllers/api/channels_controller.rb, app/javascript/app/application.scss, app/javascript/components/BotChannelWebSocket.jsx, app/javascript/components/css/_global.scss, app/javascript/utils/types-generated-decl.jsx, app/models/bot.rb, app/models/channel.rb, app/schemas/types.json, app/services/publish_bot.rb, config/initializers/shortener.rb, config/routes.rb, db/migrate/20180927150728_create_shortened_urls_table.rb, db/migrate/20180928172525_generate_web_channel_url_key.rb, db/schema.rb, spec/controllers/api/channels_controller_spec.rb, spec/models/bot_spec.rb, spec/models/channel_spec.rb, spec/services/publish_bot_spec.rb
=> Provide a web channel short link

app/javascript/components/ChatClient.jsx, app/javascript/components/WebChatClient.jsx
=> Support human override from web chat
